SELECT
fl.IIN as hashIin,
fl2.KATO_2 as KATO,
fl2.KATO_2_NAME as regionFL,
fl2.KATO_4_NAME as districtFL,
fl2.REG_ADDRESS_CITY as cityFLRu,
building.building_num as buildingFL,
fl2.REG_ADDRESS_STREET as streetFLRu,
building.flat as apartmentFL,
rpn.REGION_NAME AS regionRPN,
rpn.RAYON AS districtRPN,
rpn.CITY as cityRPNRu,
rpn.BUILDING as buildingRPN,
rpn.STREET as streetRPNRu,
rpn.FLAT as apartmentRPN,
tel.PHONENUMBER_ as phone
FROM 
(select DISTINCT IIN ,AR_CODE, CAPABLE_STATUS_ID ,REG_ADDRESS_CITY,REG_ADDRESS_BUILDING,REG_ADDRESS_STREET,REG_ADDRESS_FLAT,CITIZENSHIP_ID,PERSON_STATUS_ID,REG_ADDRESS_DISTRICTS_ID,REG_ADDRESS_REGION_ID from MU_FL.GBL_PERSON FINAL
		where REMOVED = 0 and 
		(EXCLUDE_REASON_ID is null or EXCLUDE_REASON_ID = 1)
		and CITIZENSHIP_ID = 105 and REG_ADDRESS_INVALIDITY_ID != 4 and AGE BETWEEN 25 AND 65 and (CAPABLE_STATUS_ID IS NULL OR CAPABLE_STATUS_ID IN (1,4,5)) ) fl
left join DM_ZEROS.DM_MU_GBL_PERSON_LIVE_KZ_CITZN fl2 on fl.IIN = fl2.IIN
LEFT JOIN (SELECT RCA,N_OF_BUILDING as building_num, NULL  as flat
			FROM DM_ZEROS.DM_MCRIAP_AR_S_BUILDINGS_FLAT
			union all
			SELECT RCA, N_OF_BUILDING as building_num, N_OF_FLAT as flat
			FROM DM_ZEROS.DM_MCRIAP_AR_S_BP_FLAT) AS building on fl.AR_CODE = building.RCA
LEFT JOIN TEST.mgov_iin_tel tel on fl.IIN = tel.IIN_
LEFT JOIN (
with cte as (
	SELECT distinct
	PERSONIIN ,
	CITY,
	BUILDING,
	DISTRICT_NAMERU AS REGION_NAME,
	FLAT,
	REGION_NAMERU AS RAYON,
	STREET,
	max(SDU_LOAD_IN_DT) as dat,
	ROW_NUMBER () over (partition by PERSONIIN order by dat desc) as row_num
	FROM MZ_RPN.GBDFL_ADDRESSES
	group by
	PERSONIIN ,
	CITY,
	BUILDING,
	DISTRICT_NAMERU AS REGION_NAME,
	FLAT,
	REGION_NAMERU AS RAYON,
	STREET)
	select * from cte where row_num = 1
) rpn on rpn.PERSONIIN = fl.IIN
WHERE fl.IIN not in (SELECT 
PERS.IIN 
--HD.UID AS DIAGNOSIS_UID
--, PERS.UID AS PERSON_UID
--, HD.DT_BEG AS DT_BEG 
--, PERS.SEXID AS SEX_ID 
--, CASE 
--	WHEN PERS.SEXID = 0 THEN 'Íå óêàçàí'
--	WHEN PERS.SEXID = 2 THEN 'Æåíñêèé'
--	WHEN PERS.SEXID = 3 THEN 'Ìóæñêîé'
--ELSE NULL END AS SEX_NAME
--, PERS.BIRTHDATE AS BIRTHDATE
--, HD.ICD10 AS DIAGNOSIS_ID
--, PSYCHOSIS.RUS_NAME AS PSYCHOSIS_NAME
----, NARKOSIS.RUS_NAME AS NARKOSIS_NAME
--, CHR.ISCHRONICAL AS ISCHRONICAL
FROM MZ_ERDB.HUMAN_DIAG HD 
INNER JOIN MZ_ERDB.HUMAN PERS ON HD.HUMAN_UID = PERS.UID 
	AND PERS.IIN != '4EE9CB68BAD1069BBE54103C9FBD957807CDE54A8B4BAC570A9326425D45E7B8'
INNER JOIN 
(
	SELECT MKB.*
	FROM MZ_ERDB.SPMKB MKB
	WHERE (toInt16OrNull(trimRight(F2)) BETWEEN 0 AND 9 OR toInt16OrNull(trimRight(F2)) BETWEEN 20 AND 99)
		AND F1 = 'F  '
) PSYCHOSIS ON HD.ICD10 = PSYCHOSIS.ID

/* 
INNER JOIN 
(
	SELECT MKB.*
	FROM MZ_ERDB.SPMKB MKB
	WHERE (toInt16OrNull(trimRight(F2)) BETWEEN 10 AND 19)
		AND F1 = 'F  '
) NARKOSIS ON HD.ICD10 = NARKOSIS.ID
*/

LEFT JOIN MZ_ERDB.SP_DISEASESBYCATEGORIES CHR ON CHR.MKBID = HD.ICD10 
left join MZ_ERDB.SP_PRICH_END reason on reason.ID = HD.PRICH_END_ID
WHERE --HD.DT_BEG >= '2017-01-01 00:00:00'
	HD.DT_END IS NULL 
	AND HD.DT_DELETE IS NULL and reason.ID != 4)
and regionFL is not null