--ЗАЛОЖЕННЫЕ ИМУЩЕСТВА
SELECT * FROM(
SELECT 
DISTINCT T1.KATO AS KATO,
COUNT(T1.DESC_TYPE_OF_PROPERTY) AS COUNT_ZALOZH,
T1.DESC_TYPE_OF_PROPERTY,
T2.FULL_KATO_NAME ,
T2.KATO_2 ,
T2.KATO_2_NAME ,
T2.KATO_4 ,
T2.KATO_4 ,
T2.KATO_4_NAME,
T2.KATO_6 ,
multiIf(T2.KATO_6_NAME LIKE '%с.о.%', trim(LEADING 'с.о.' FROM trim(TRAILING 'с.о.' FROM T2.KATO_6_NAME)),
		T2.KATO_6_NAME LIKE '%п.а.%', trim(LEADING 'п.а.' FROM trim(TRAILING 'п.а.' FROM T2.KATO_6_NAME)),
		T2.KATO_6_NAME LIKE '%с.а.%', trim(LEADING 'с.а.' FROM trim(TRAILING 'с.а.' FROM T2.KATO_6_NAME)),
		T2.KATO_6_NAME LIKE '%c.о.%', trim(LEADING 'с.о.' FROM trim(TRAILING 'с.о.' FROM T2.KATO_6_NAME)),
		T2.KATO_6_NAME LIKE '%г.а.%', trim(LEADING 'г.а.' FROM trim(TRAILING 'г.а.' FROM T2.KATO_6_NAME)),
		T2.KATO_6_NAME) AS KATO6_NAME_RUS,
T2.FULL_KATO_NAME,
T2.NAME_OF_DELENIYA
FROM DM_ZEROS.DM_MU_RN_PROPERTY_IIN_RN T1
INNER JOIN DM_ZEROS.DIC_KATO_REF_NAME_DELENIYA T2 ON T1.KATO = T2.FULL_KATO
INNER JOIN DM_ZEROS.DM_MU_RN_PROPERTY_IIN_OBR_RN OBR ON T1.UH_OH = OBR.UH_OH
where T2.FULL_KATO_NAME NOT like '%с.о.%'
group by T1.DESC_TYPE_OF_PROPERTY,KATO, T2.FULL_KATO_NAME ,T2.KATO_2 ,T2.KATO_2_NAME ,T2.KATO_4 ,T2.KATO_4 ,T2.KATO_4_NAME,T2.KATO_6 ,KATO6_NAME_RUS,T2.FULL_KATO_NAME,T2.NAME_OF_DELENIYA
order by KATO
) ZALOZH
LEFT JOIN (
SELECT 
DISTINCT T1.KATO AS KATO,
COUNT(T1.DESC_TYPE_OF_PROPERTY) AS COUNT_OBSH,
T1.DESC_TYPE_OF_PROPERTY AS OBSH_DESC_TYPE_OF_PROPERTY,
multiIf(T2.KATO_6_NAME LIKE '%с.о.%', trim(LEADING 'с.о.' FROM trim(TRAILING 'с.о.' FROM T2.KATO_6_NAME)),
		T2.KATO_6_NAME LIKE '%п.а.%',trim(LEADING 'п.а.' FROM trim(TRAILING 'п.а.' FROM T2.KATO_6_NAME)),
		T2.KATO_6_NAME LIKE '%с.а.%', trim(LEADING 'с.а.' FROM trim(TRAILING 'с.а.' FROM T2.KATO_6_NAME)),
		T2.KATO_6_NAME LIKE '%c.о.%', trim(LEADING 'c.о.' FROM trim(TRAILING 'c.о.' FROM T2.KATO_6_NAME)),
		T2.KATO_6_NAME LIKE '%г.а.%', trim(LEADING 'г.а.' FROM trim(TRAILING 'г.а.' FROM T2.KATO_6_NAME)),
		T2.KATO_6_NAME) AS KATO6_NAME_RUS,
T2.FULL_KATO_NAME
FROM DM_ZEROS.DM_MU_RN_PROPERTY_IIN_RN T1
INNER JOIN DM_ZEROS.DIC_KATO_REF_NAME_DELENIYA T2 ON T1.KATO = T2.FULL_KATO
where T2.FULL_KATO_NAME NOT like '%с.о.%'
group by T1.DESC_TYPE_OF_PROPERTY,KATO, T2.FULL_KATO_NAME ,T2.KATO_2 ,T2.KATO_2_NAME ,T2.KATO_4 ,T2.KATO_4 ,T2.KATO_4_NAME,T2.KATO_6 ,KATO6_NAME_RUS,T2.FULL_KATO_NAME,T2.NAME_OF_DELENIYA
ORDER BY KATO
) OBSH ON ZALOZH.KATO = OBSH.KATO AND ZALOZH.T1.DESC_TYPE_OF_PROPERTY = OBSH.OBSH_DESC_TYPE_OF_PROPERTY
ORDER BY KATO