SELECT
GBL.IIN AS IIN,
GBL.PERSON_AGE AS AGE,
GBL.BIRTH_DATE AS BIRTHDATE,
GBL.SEX_ID AS SEX_ID,
GBL.NATIONALTY_ID AS NATIONALITY_ID,
GBL.SEX_NAME AS SEX_NAME,
GBL.NATIONALTY_NAME AS NATIONALITY_NAME,
GBL.ABLE_POPULATION AS ABLE_POPULATION,
round(AVG(OPV.AMOUNT),2) AS AMOUNT,
ZAGS.MARRIAGE_FLAG AS MARRIAGE_FLAG,
K.*,
VS.VALUE_RUS 
FROM DM_ZEROS.DM_MU_GBL_PERSON_LIVE_KZ_CITZN GBL
LEFT JOIN(
	SELECT DISTINCT WOMAN_NAME as NAME, WOMAN_SURNAME AS SURNAME, WOMAN_BIRTH_DATE AS BIRTH_DATE , 'В БРАКЕ' AS MARRIAGE_FLAG FROM DM_ZEROS.DM_ZAGS_BRAKI_IN_FL_PERSON
	UNION ALL
	SELECT DISTINCT MAN_NAME AS NAME, MAN_SURNAME AS SURNAME, MAN_BIRTH_DATE AS BIRTH_DATE, 'В БРАКЕ' AS MARRIAGE_FLAG FROM DM_ZEROS.DM_ZAGS_BRAKI_IN_FL_PERSON
	UNION ALL
	SELECT DISTINCT WOMAN_NAME as NAME, WOMAN_SURNAME AS SURNAME, WOMAN_BIRTH_DATE AS BIRTH_DATE , 'РАЗВЕДЕН (-А)' AS MARRIAGE_FLAG FROM DM_ZEROS.DM_DEVORCED_IN_FL_PERSON
	UNION ALL
	SELECT DISTINCT MAN_NAME AS NAME, MAN_SURNAME AS SURNAME, MAN_BIRTH_DATE AS BIRTH_DATE, 'РАЗВЕДЕН (-А)' AS MARRIAGE_FLAG FROM DM_ZEROS.DM_DEVORCED_IN_FL_PERSON
	) AS ZAGS
	ON GBL.FIRSTNAME = ZAGS.NAME AND GBL.SURNAME = ZAGS.SURNAME AND GBL.BIRTH_DATE = ZAGS.BIRTH_DATE
		left join DM_ZEROS.DIC_KATO_REF K on GBL.KATO = K.FULL_KATO
			LEFT JOIN (
			SELECT SUM(AMOUNT)*10 AS AMOUNT, PERIOD ,RNN FROM DM_ZEROS.DM_MTSZN_PAYSYS_OPV_IIN_BIN_YEAR GROUP BY PERIOD,RNN) AS OPV
			ON GBL.IIN = OPV.RNN
				LEFT JOIN DICTIONARY.SELSKIE_OKRUGA_VALUE_RUS VS ON GBL.KATO = VS.KATO 
WHERE K.TYPE_OF_LOCATION IN ('RURAL_COUNTY', 'TOWN','RURAL_ST','TOWN_A')
group by GBL.IIN AS IIN,
GBL.PERSON_AGE AS AGE,
GBL.BIRTH_DATE AS BIRTHDATE,
GBL.SEX_ID AS SEX_ID,
GBL.NATIONALTY_ID AS NATIONALITY_ID,
GBL.SEX_NAME AS SEX_NAME,
GBL.NATIONALTY_NAME AS NATIONALITY_NAME,
GBL.ABLE_POPULATION AS ABLE_POPULATION,
ZAGS.MARRIAGE_FLAG AS MARRIAGE_FLAG,
K.FULL_KATO ,
K.FULL_KATO_NAME ,
K.KATO_2 ,
K.KATO_2_NAME ,
K.KATO_4 ,
K.KATO_4_NAME ,
K.KATO_6 ,
K.KATO_6_NAME ,
K.TYPE_OF_LOCATION,
K.SDU_LOAD_IN_DT,
VS.VALUE_RUS 