create table DM_ANALYTICS.SELSKIE_OKRUGA_ZP1 ENGINE = Log as 
SELECT
fam.FAMILY_IIN as FAMILY_IIN
, zp.MEAN_ZP 
, zp.ZP_CATEGORY as ZP_CATEGORY
, MIN(zp.MEAN_ZP) as MINZP
, MAX(zp.MEAN_ZP) as MAXZP
, quantile(zp.MEAN_ZP) as MEDIAN
, round(AVG(zp.MEAN_ZP),2) AS AVERAGE
, arrayElement(topK(1)(zp.MEAN_ZP),1) AS MODE
, sel.ABLE_POPULATION
, sel.WORK_POPULATION
, sel.KATO as KATO
, sel.KATO2 as KATO2
, sel.REGION_NAME as REGION_NAME
, sel.KATO4 as KATO_4
, sel.KATO4_NAME as KATO_4_NAME
, sel.KATO6 as KATO_6
, sel.KATO6_NAME as KATO_6_NAME
, sel.KATO_NAME as FULL_KATO_NAME
from DM_ANALYTICS.SELSKIY_OKRUG_FL_AR sel
left join DM_MINTRUD.IIN_WITH_FL_IIN fam on sel.IIN = fam.IIN
left join DM_MINTRUD.MEAN_ZP_PER_FAMILY zp on fam.FAMILY_IIN = zp.FAMILY_IIN
where FAMILY_IIN is not null
group by 
FAMILY_IIN, zp.MEAN_ZP, ZP_CATEGORY, ABLE_POPULATION, WORK_POPULATION, 
KATO, KATO2, REGION_NAME, 
KATO4, KATO4_NAME, KATO6, 
KATO6_NAME, KATO_NAME