--РАБОТАЮЩИЙ
SELECT
count(A.RNN) as `COUNT`,
MIN(A.AMOUNT),
MAX(A.AMOUNT),
quantile(A.AMOUNT) as MEDIAN,
round(AVG(A.AMOUNT),2) AS AVERAGE,
arrayElement(topK(1)(A.AMOUNT),1) AS MODE,
K.KATO as KATO,
K.FULL_KATO_NAME AS FULL_KATO_NAME,
K.KATO_2 AS KATO_2,
K.KATO_2_NAME AS KATO_2_NAME,
K.KATO_4 AS KATO_4,
K.KATO_4_NAME AS KATO_4_NAME,
K.KATO_6 AS KATO_6,
K.KATO_6_NAME AS KATO_6_NAME,
KTO.TYPE_OF_LOCATION
FROM 
	(SELECT
	RNN,
	round(AVG(AMOUNT),2) AS AMOUNT
	FROM
		(SELECT RNN ,PERIOD ,SUM(AMOUNT)*10 AS AMOUNT 
		FROM DM_ZEROS.DM_MTSZN_PAYSYS_OPV_IIN_BIN_YEAR_TEST
		GROUP BY RNN ,PERIOD) 
	GROUP BY RNN) as A
LEFT JOIN DM_ZEROS.DM_MU_GBL_PERSON_LIVE_KZ_CITZN_sample K ON A.RNN = K.IIN
LEFT JOIN DM_ZEROS.DIC_KATO_REF KTO ON KATO=KTO.FULL_KATO
GROUP BY
K.KATO,
K.FULL_KATO_NAME,
K.KATO_2,
K.KATO_2_NAME,
K.KATO_4,
K.KATO_4_NAME,
K.KATO_6,
K.KATO_6_NAME,
KTO.TYPE_OF_LOCATION

--ВСЕГО
SELECT
count(DISTINCT K.IIN) as `COUNT`,
MIN(AMOUNT),
MAX(AMOUNT),
quantile(AMOUNT) as MEDIAN,
round(AVG(AMOUNT),2) AS AVERAGE,
arrayElement(topK(1)(AMOUNT),1) AS MODE,
K.KATO AS KATO,
K.FULL_KATO_NAME AS FULL_KATO_NAME,
K.KATO_2 AS KATO_2,
K.KATO_2_NAME AS KATO_2_NAME,
K.KATO_4 AS KATO_4,
K.KATO_4_NAME AS KATO_4_NAME,
K.KATO_6 AS KATO_6,
K.KATO_6_NAME AS KATO_6_NAME,
dkr.TYPE_OF_LOCATION AS VALUE_RUS,
'Все люди' as FUNC_ZNACHENIYA
FROM 
	(SELECT *, if(A.AMOUNT is NULL,0,AMOUNT) AS AMOUNT FROM DM_ZEROS.DM_MU_GBL_PERSON_LIVE_KZ_CITZN_sample K
	left join (SELECT RNN ,PERIOD ,SUM(AMOUNT)*10 AS AMOUNT 
				FROM DM_ZEROS.DM_MTSZN_PAYSYS_OPV_IIN_BIN_YEAR_TEST  
					GROUP BY RNN ,PERIOD) as A on K.IIN  = A.RNN
left join DM_ZEROS.DIC_KATO_REF dkr ON K.KATO =dkr.FULL_KATO
where dkr.TYPE_OF_LOCATION IN ('RURAL_COUNTY', 'TOWN','RURAL_ST','TOWN_A') AND K.KATO IS NOT NULL)
GROUP BY
K.KATO,
K.FULL_KATO_NAME,
K.KATO_2,
K.KATO_2_NAME,
K.KATO_4,
K.KATO_4_NAME,
K.KATO_6,
K.KATO_6_NAME,
dkr.TYPE_OF_LOCATION

--ТРУДОСПОСОБНЫЕ
SELECT
count(DISTINCT K.IIN) as `COUNT`,
MIN(AMOUNT),
MAX(AMOUNT),
quantile(AMOUNT) as MEDIAN,
round(AVG(AMOUNT),2) AS AVERAGE,
arrayElement(topK(1)(AMOUNT),1) AS MODE,
K.KATO AS KATO,
K.FULL_KATO_NAME AS FULL_KATO_NAME,
K.KATO_2 AS KATO_2,
K.KATO_2_NAME AS KATO_2_NAME,
K.KATO_4 AS KATO_4,
K.KATO_4_NAME AS KATO_4_NAME,
K.KATO_6 AS KATO_6,
K.KATO_6_NAME AS KATO_6_NAME,
dkr.TYPE_OF_LOCATION AS VALUE_RUS,
'Трудоспособные' as FUNC_ZNACHENIYA
FROM 
	(SELECT *, if(A.AMOUNT is NULL,0,AMOUNT) AS AMOUNT FROM DM_ZEROS.DM_MU_GBL_PERSON_LIVE_KZ_CITZN_sample K
	left join (SELECT RNN ,PERIOD ,SUM(AMOUNT)*10 AS AMOUNT 
				FROM DM_ZEROS.DM_MTSZN_PAYSYS_OPV_IIN_BIN_YEAR_TEST  
					GROUP BY RNN ,PERIOD) as A on K.IIN  = A.RNN
left join DM_ZEROS.DIC_KATO_REF dkr ON K.KATO =dkr.FULL_KATO
where dkr.TYPE_OF_LOCATION IN ('RURAL_COUNTY', 'TOWN','RURAL_ST','TOWN_A') AND ABLE_POPULATION = 'Трудоспособные' AND K.KATO IS NOT NULL)
GROUP BY
K.KATO,
K.FULL_KATO_NAME,
K.KATO_2,
K.KATO_2_NAME,
K.KATO_4,
K.KATO_4_NAME,
K.KATO_6,
K.KATO_6_NAME,
dkr.TYPE_OF_LOCATION