SELECT A.OWNER as OWNER,
A.ANIMAL_KIND_ID  as ANIMALKINDID ,
B.NAMERU AS NAMERU,
COUNT(ANIMALKINDID) AS KOLVO,
SUM(B.PRICE) AS  SUMMA
FROM MSH_ISZH.LPH_HIST  A
LEFT JOIN MSH_ISZH.ANIMAL_DESC1 B ON A.ANIMAL_KIND_ID = toInt16(B.ID)  WHERE OWNER !=''  and A.STATUS  = 1
GROUP BY OWNER,ANIMALKINDID,NAMERU